# Generated by Django 5.1.6 on 2025-06-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0018_coin_price_per_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_per_token',
            field=models.BigIntegerField(default=25),
        ),
    ]
