# Generated by Django 5.1.6 on 2025-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0022_alter_coin_total_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='total_supply',
            field=models.DecimalField(decimal_places=9, max_digits=32),
        ),
    ]
