# Generated by Django 5.1.6 on 2025-07-05 09:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0023_alter_coin_total_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerscore',
            name='last_monthly_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderscore',
            name='flash_dumps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='flash_pnd_last_check',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='last_monthly_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traderscore',
            name='snipe_dumps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='snipe_last_check',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='total_portfolio_growth_per_month',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='valid_held_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traderscore',
            name='valid_long_term_holding',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CoinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=88)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('coin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coin_history', to='systems.coin')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='systems_coi_created_807f1a_idx'), models.Index(fields=['key'], name='systems_coi_key_de7c06_idx')],
            },
        ),
        migrations.CreateModel(
            name='TraderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=88)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='systems_tra_created_8b7a5b_idx'), models.Index(fields=['key'], name='systems_tra_key_3bfc71_idx')],
            },
        ),
    ]
