# Generated by Django 5.1.6 on 2025-07-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0024_developerscore_last_monthly_update_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraderHistory',
        ),
    ]
