# Generated by Django 5.1.6 on 2025-07-05 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0025_delete_traderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=88)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='systems_tra_created_8b7a5b_idx'), models.Index(fields=['key'], name='systems_tra_key_3bfc71_idx')],
            },
        ),
    ]
