# Generated by Django 5.1.6 on 2025-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0027_alter_coinhistory_coin_alter_traderhistory_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='change',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='coin',
            name='current_marketcap',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='end_marketcap',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coin',
            name='start_marketcap',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='address',
            field=models.CharField(max_length=44, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='transaction_hash',
            field=models.CharField(max_length=88, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='traderscore',
            name='flash_pnd_last_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
