# Generated by Django 5.1.6 on 2025-07-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0028_coin_change_coin_current_marketcap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='change',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=24),
        ),
    ]
