# Generated by Django 5.1.6 on 2025-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0029_alter_coin_change_alter_coin_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceApi',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sol_price', models.DecimalField(decimal_places=8, default=150, max_digits=20)),
            ],
        ),
    ]
