# Generated by Django 5.1.6 on 2025-08-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0029_alter_coin_change_alter_coin_current_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='price_per_token',
        ),
        migrations.AddField(
            model_name='coin',
            name='migrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coin',
            name='migration_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='raydium_pool',
            field=models.CharField(max_length=44, null=True),
        ),
    ]
