# Generated by Django 5.1.6 on 2025-08-13 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0030_remove_coin_price_per_token_coin_migrated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coin',
            name='migration_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
