# Generated by Django 5.1.6 on 2025-08-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0030_priceapi'),
        ('systems', '0031_coin_updated_alter_coin_migration_timestamp_and_more'),
    ]

    operations = [
    ]
