# Generated by Django 5.1.6 on 2025-08-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0032_merge_20250815_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='total_held',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=32),
        ),
    ]
