# Generated by Django 5.1.6 on 2025-08-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0033_coin_total_held'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solanauser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='solanauser',
            name='last_name',
        ),
    ]
