# Generated by Django 5.1.6 on 2025-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0034_remove_solanauser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindrcscore',
            name='last_held_percent',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='last_price',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='last_recorded_price',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='coindrcscore',
            name='max_volume_recorded',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
        migrations.AlterField(
            model_name='trade',
            name='coin_amount',
            field=models.DecimalField(decimal_places=9, max_digits=24),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sol_amount',
            field=models.DecimalField(decimal_places=9, max_digits=24),
        ),
        migrations.AlterField(
            model_name='traderscore',
            name='total_portfolio_growth_per_month',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=24),
        ),
    ]
