# Generated by Django 5.1.6 on 2025-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0035_alter_coindrcscore_last_held_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trading_fee',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
            preserve_default=False,
        ),
    ]
