# Generated by Django 5.1.6 on 2025-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0036_trade_trading_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trading_fee',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=24),
        ),
    ]
