# Generated by Django 5.1.6 on 2025-09-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0037_alter_trade_trading_fee'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coin',
            index=models.Index(fields=['creator', '-created_at'], name='idx_creator_created_at'),
        ),
    ]
