# Generated by Django 5.1.6 on 2025-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0038_coin_idx_creator_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usercoinholdings',
            index=models.Index(fields=['user', 'coin'], name='systems_use_user_id_57e050_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoinholdings',
            index=models.Index(fields=['user'], name='systems_use_user_id_d1cab8_idx'),
        ),
    ]
