# Generated by Django 5.1.6 on 2025-10-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0039_usercoinholdings_systems_use_user_id_57e050_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerscore',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
